config/routes.rb
Rails.application.routes.draw do

  root :to => 'bands#index'

  resources :users, only: [:create, :new, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]

  resource :session, only: [:create, :destroy, :new]

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  album_id   :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  bonus      :boolean          not null
#  lyrics     :text
#

class Track < ActiveRecord::Base
  validates :title, :album_id, presence: true
  validates :bonus, :inclusion => {:in => [true, false]}


  belongs_to :album, :inverse_of => :tracks, dependent: :destroy

  has_many :notes
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :check_log_in

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @album = Album.find(params[:album_id])
    @track = @album.tracks.new
    render :new
  end

  def create
    @album = Album.find(track_params[:album_id])
    @track = @album.tracks.new(track_params)
    if @track.save
      flash[:notice] = "Track saved to album!"
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @album = @track.album
    render :new
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      flash[:notice] = "Track updated!"
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  private
  def track_params
    params.require(:track).permit(:title, :album_id, :bonus, :lyrics)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/new.html.erb
<% if @track.persisted? %>
  <form action="<%= track_url(@track) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <h1>Edit <%= @track.name %></h1>
<% else %>
  <form action="<%= tracks_url(@track) %>" method="POST">
    <h1>Add a Track to <%= @album.name %></h1>
<% end %>

  <% if !!@track.errors.full_messages %>
    <ul><% @track.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    </ul>
    <% end %>
  <% end %>
    <%= auth_token %>
    <br><br>
    <input type="hidden"
      name="track[album_id]"
      value="<%= @album.id %>">

    <label for="track_title">Title</label>
    <input
    type="text"
    name="track[title]"
    id="track_title"
    value="<%= @track.title %>">
    <br><br>

    <label for="bonus_track">Bonus Track</label>
    <input
      type="radio"
      name="track[bonus]"
      id="bonus_track"
      value="true"
      <%= "checked" if @track.bonus %>>

    <label for="reg_track">Regular Track</label>
    <input
      type="radio"
      name="track[bonus]"
      id="reg_track"
      value="false"
      <%= "checked" unless @track.bonus %>>

    <br>
    <label for="lyric_box">Enter lyrics</label>
    <textarea
      name="track[lyrics]"
      id="lyric_box"
      value="<%= @track.lyrics %>">
    </textarea>

    <br>
    <input type="submit" value="Save this track">
  </form>

app/views/tracks/show.html.erb
<h1><%= @track.album.band.name %> - <%= @track.album.name %></h1>
"<%= @track.title %>"
<br>
<br>
---------
<br><%= ugly_lyrics(@track.lyrics) %><br>
---------
<br>

<br>
<a href="<%= edit_track_url(@track) %>">Edit this track</a>
<br>
<% @track.notes.each do |note| %>
<%= render 'notes/note', note: note %>
<% end %>
<%= render 'notes/form', track: @track %><br>
<a href="<%= band_url(@track.album.band) %>">Back to <%= @track.album.band.name %></a><br>
<a href="<%= album_url(@track.album) %>">Back to <%= @track.album.name %></a>