config/routes.rb
Rails.application.routes.draw do

  root :to => 'bands#index'

  resources :users, only: [:create, :new, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]

  resource :session, only: [:create, :destroy, :new]

end

app/views/shared/_account_form.html.erb
  <%= auth_token %>

  <label for="user_email">Email</label>
  <input
    id="user_email"
    name="user[email]"
    type="text"
    value="<%= @user.email %>">
  <br>

  <label for="user_password">Password</label>
  <input
    id="user_password"
    name="user[password]"
    type="password">
  <br>

app/views/shared/_band_list.html.erb
<select name="album[band_id]">
  <% Band.all.each do |band| %>
    <option
      value="<%= band.id %>"
      <%= default_band?(band) %>>
      <%= band.name %>
    </option>
  <% end %>
</select>

app/views/shared/_login.html.erb
<% if current_user.nil? %>
  <%= button_to "Sign in", new_session_url, method: :get %> or
  <%= button_to "Sign up", new_user_url, method: :get %>
<% else %>
  Logged in as: <%= current_user.email %>
  <%= button_to "Logout", session_url, method: :delete %>
<% end %>

app/views/shared/_navbar.html.erb
<% unless request.env['PATH_INFO'] == "/bands"%>
<a href="<%= bands_url %>">Back to the Nightvale Roster</a>
<% end %>