config/routes.rb
Rails.application.routes.draw do

  root :to => 'bands#index'

  resources :users, only: [:create, :new, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]

  resource :session, only: [:create, :destroy, :new]

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  band_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  live       :boolean          not null
#
# Indexes
#
#  index_albums_on_name  (name) UNIQUE
#

class Album < ActiveRecord::Base
  validates :name, :band_id, presence: true
  validates :live, :inclusion => {:in => [true, false]}

  has_many :tracks, :inverse_of => :album, dependent: :destroy
  belongs_to :band, :inverse_of => :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :check_log_in

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = @band.albums.new
    render :new
  end

  def create
    @band = Band.find(album_params[:band_id])
    @album = @band.albums.new(album_params)
    if @album.save
      flash[:notice] = "Album saved!"
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:band_id])
    @album = band.albums.find(params[:id])
    render :new
  end

  def update
    if @album.update(album_params)
      redirect_to band_url(@album.band)
    else
      flash.new[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id, :live)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def default_band?(band)
    "selected" if @album.band == band
  end
end

app/views/albums/_track_list.html.erb
<ul>
  <% unless album.tracks.empty? %>
    <% album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
    <% end %>
  <% end %>
</ul>

app/views/albums/new.html.erb
<h1>Add an Album to the Nightvale Catalog</h1>

<% if !!@album.errors.full_messages %>
  <ul><% @album.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
  </ul>
  <% end %>
<% end %>

  <% if @album.persisted? %>
    <form action="<%= album_url(@album) %>" method="POST">
      <input type="hidden" name="_method" value="PATCH">
  <% else %>
    <form action="<%= albums_url(@album) %>" method="POST">
  <% end %>
      <%= auth_token %>
      <%= render 'shared/band_list' %>
      <br><br>

      <label for="album_name">Title</label>
      <input
      type="text"
      name="album[name]"
      id="album_name"
      value="<%= @album.name %>">
      <br><br>

      <label for="live_album">Live</label>
      <input
        type="radio"
        name="album[live]"
        id="live_album"
        value="true"
        <%= "checked" if @album.live == "live" %>>

      <label for="studio_album">Studio</label>
      <input
        type="radio"
        name="album[live]"
        id="studio album"
        value="false"
        <%= "checked" if @album.live == "studio" %>>
      <br>

      <input type="submit" value="Save this album">
    </form>

app/views/albums/show.html.erb
<h1><%= @album.band.name%> - <%= @album.name %></h1>

<%= render 'track_list', album: @album %>
<br>
<a href="<%= new_album_track_url(@album) %>">Add a track to this album</a>
<a href="<%= band_url(@album.band) %>">
  Back to the page for <%= @album.band.name %>
</a>