config/routes.rb
Rails.application.routes.draw do

  root :to => 'bands#index'

  resources :users, only: [:create, :new, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]

  resource :session, only: [:create, :destroy, :new]

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_bands_on_name  (name) UNIQUE
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, :inverse_of => :band, dependent: :destroy
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter :check_log_in

  def index
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :new
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end


end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_album_list.html.erb
<ul><strong>Albums</strong>
<% unless band.albums.empty? %>
  <% band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><%= album.name %></a>
      <%= render 'albums/track_list', album: album %>
    </li>
  <% end %>
<% end %>
</ul>
<a href="<%= new_band_album_url(band) %>">Add an Album</a>

app/views/bands/index.html.erb
<h1>Nightvale Roster</h1>
<ul>
  <% Band.all.each do |band| %>
  <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
</ul>

<a href="<%= new_band_url %>">Add a band to the Nightvale database</a>

app/views/bands/new.html.erb
<% if @band.persisted? %>
  <form action="<%= band_url(@band) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <h1>Edit <%= @band.name %></h1>
<% else %>
  <form action="<%= bands_url %>" method="POST">
    <h1>Add a Band to the Nightvale Catalog</h1>
<% end %>
<% if !!@band.errors.full_messages %>
  <ul><% @band.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
  </ul>
  <% end %>
<% end %>
    <%= auth_token %>
    <label for="band_name">Band Name</label>
    <input
      id="band_name"
      name="band[name]"
      type="text"
      value="<%= @band.name %>">
    <br>

    <input type="submit" value="Submit Band!">
  </form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<%= render 'album_list', band: @band %>
<br>

<a href="<%= edit_band_url(@band) %>">Change this band's details</a>
<br>

<form action="<% band_url(@band) %>" method="POST">
  <%= auth_token %>
  <input
    type="hidden"
    name="_method"
    value="DELETE">
  <input type="submit" value="DELETE">
</form>
<br>